apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: quay.io/gpte-devops-automation/coffee-shop-placeholder:latest

