---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- ./buildconfig.yaml
- ./imagestream.yaml

patches:
- ./deployment-patches.yaml

configMapGenerator:
- name: coffee-shop
  envs:
  - ./configmap.env

