apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: homework-nexus-registry.apps.shared-dev4.dev4.openshift.opentlc.com/7d7sr-barista:prod-2021-12-03-04-00-33

