apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop
spec:
  template:
    spec:
      containers:
      - name: coffee-shop
        image: homework-nexus-registry.apps.shared-dev4.dev4.openshift.opentlc.com/7d7sr-coffee-shop:prod-2021-12-03-03-53-54

